### ISSUE TITLE
wrong degree count with singleton

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#190]
Running 
```python
HH = xgi.Hypergraph([{1, 2, 3}, {4}, {5, 6}, {6, 7, 8}])
xgi.degree_counts(HH)
```
outputs `[0, 7, 1]`.

It is even our test: https://github.com/ComplexGroupInteractions/xgi/blob/c262f406cf13e3d51e7b40e5534fbfcca223caff/tests/classes/test_function.py#L58).

But node 4 does not have any neighbour, so degree 0 should have count 1: the output should be `[1, 6, 1]`.

**Comment by leotrs** [comment]
I think the rationale is that 4 belongs to one (singleton) edge. So in a
way, it is correct. The fix would be to add a parameter "ignore_singletons"
as is done elsewhere in the codebase.

**Comment by leotrs** [comment]
It comes down to a matter of semantics/perspective. Is the degree the number of neighboring nodes? If so, do you count repetitions (when a neighbor appears in many different edges)? Or is the degree defined as the number of edges a node belongs to?

Since we are using the bipartite representation, I'd say the degree of a node in the hypergraph should just be the degree of the node in the bipartite representation, and in this case it is 1 because it belongs to exactly one hyperedge.

**Comment by maximelucas** [comment]
Ok I see where this is coming from now, thanks. 
Might just touch on this in next meeting to make sure it makes sense for everyone, and maybe specify in docs? This particular case of the singleton still feels weird to me even though I understand the bipartite reason 😅

**Comment by leotrs** [comment]
Agreed, let's put it in the agenda.

**Comment by iaciac** [comment]
I can totally share Max's doubts, but I also completely agree with the "clean" definition by Leo of degree as given by the bipartite. I would say that the only thing really needed at this point is to stress this example as much as possible in the documentation ;)

**Comment by leotrs** [comment]
Agreed, at this point we should just pick one and stick with it.

(Though, if I may add one more data point: in graphs with self-loops, usually a node's degree is increased by 2 if it has a self-loop...)

**Comment by maximelucas** [comment]
If I remember correctly, we decided to simply add an explanation in the docstring for this, right?

**Comment by leotrs** [comment]
Yes!
