### ISSUE TITLE
Remove `create_using` from hypergraph conversion methods

### ISSUE THREAD

**Issue by nwlandry** [ComplexGroupInteractions/xgi#45]
For the methods in the `convert.py` file, the `create_using` keyword is used to indicate the constructor to be used to add edges from. This may be unnecessary and potentially should be implemented differently.

**Comment by leotrs** [comment]
I looked into this today and it is not possible to completely get rid of `create_using`, even when I die a little when I see it.

The reason is that the constructor of  `Hypergraph` calls some of the `convert` functions, and those need to populate a hypergraph that already exists rather than return a new hypergraph. Closing this.

**Comment by maximelucas** [comment]
Ouch. Not even with fixing #327 ?

**Comment by leotrs** [comment]
Nope. Unrelated issue.
